data_timeout = 1
window_size = 10

[serial]
path = "/dev/ttys005"
baud = 9600

[[commands]]
name = "Power on check"
command = "pow"
color = "Blue"

[[commands]]
name = "Lift-off"
command = "liftoff"
color = "Orange"

[[commands]]
name = "Abort"
command = "abort"
color = "Red"

[[graphs.Voltage.plots]]
name = "Voltage"
source_name = "volt"
color = "Orange"

[[graphs.Accelerometer.plots]]
name = "X"
source_name = "gx"
color = "Red"

[[graphs.Accelerometer.plots]]
name = "Y"
source_name = "gy"
color = "Green"

[[graphs.Accelerometer.plots]]
name = "Z"
source_name = "gz"
color = "Yellow"

[[graphs.VOT.plots]]
name = "VOT"
source_name = "vot"
color = "Blue"

[[graphs.Math.plots]]
name = "Sine"
source_name = "sin"
color = "Red"

[[graphs.Math.plots]]
name = "Cosine"
source_name = "cos"
color = "Blue"

[[graphs.Counter.plots]]
name = "Frame #"
source_name = "ctr"
color = "Green"