data_timeout = 1
window_size = 10

[serial]
path = "/dev/ttys005"
baud = 9600

[[commands]]
name = "Setpoint +"
command = "s+"
color = "Blue"

[[commands]]
name = "Setpoint -"
command = "s-"
color = "Blue"

[[commands]]
name = "P Gain +"
command = "p+"
color = "Orange"

[[commands]]
name = "P Gain -"
command = "p-"
color = "Orange"

[[commands]]
name = "I Gain +"
command = "i+"
color = "Green"

[[commands]]
name = "I Gain -"
command = "i-"
color = "Green"

[[commands]]
name = "D Gain +"
command = "d+"
color = "Yellow"

[[commands]]
name = "D Gain -"
command = "d-"
color = "Yellow"

[[graphs.VOT.plots]]
name = "VOT"
source_name = "vot"
color = "Blue"

[[graphs.Gyroscope.plots]]
name = "gX"
source_name = "gx"
color = "Red"

[[graphs.Gyroscope.plots]]
name = "gY"
source_name = "gy"
color = "Green"

[[graphs.Gyroscope.plots]]
name = "gZ"
source_name = "gz"
color = "Yellow"

[[graphs.Accelerometer.plots]]
name = "raw aX"
source_name = "ax"
color = "Red"

[[graphs.Accelerometer.plots]]
name = "aY"
source_name = "ay"
color = "Green"

[[graphs.Accelerometer.plots]]
name = "aZ"
source_name = "az"
color = "Yellow"

[[graphs.HPAccelerometer.plots]]
name = "high aX"
source_name = "hpax"
color = "Red"

[[graphs.HPAccelerometer.plots]]
name = "aY"
source_name = "hpay"
color = "Green"

[[graphs.HPAccelerometer.plots]]
name = "aZ"
source_name = "hpaz"
color = "Yellow"

[[graphs.LPAccelerometer.plots]]
name = "low aX"
source_name = "lpax"
color = "Red"

[[graphs.LPAccelerometer.plots]]
name = "aY"
source_name = "lpay"
color = "Green"

[[graphs.LPAccelerometer.plots]]
name = "aZ"
source_name = "lpaz"
color = "Yellow"

[[graphs.Kalman.plots]]
name = "Rot"
source_name = "estrot"
color = "Red"

[[graphs.Kalman.plots]]
name = "Pos"
source_name = "estpos"
color = "Blue"

[[graphs.Covariance.plots]]
name = "11"
source_name = "cov11"
color = "Red"

[[graphs.Covariance.plots]]
name = "12"
source_name = "cov12"
color = "Blue"

[[graphs.Covariance.plots]]
name = "21"
source_name = "cov21"
color = "Green"

[[graphs.Covariance.plots]]
name = "22"
source_name = "cov22"
color = "Yellow"

[[graphs.PIDGains.plots]]
name = "P"
source_name = "pgain"
color = "Red"

[[graphs.PIDGains.plots]]
name = "I"
source_name = "igain"
color = "Blue"

[[graphs.PIDGains.plots]]
name = "D"
source_name = "dgain"
color = "Green"

[[graphs.Control.plots]]
name = "Setpoint"
source_name = "set"
color = "Blue"

[[graphs.Control.plots]]
name = "Position"
source_name = "estpos"
color = "Red"

[[graphs.Control.plots]]
name = "Steady state error"
source_name = "sse"
color = "Yellow"

[[graphs.Control.plots]]
name = "Control"
source_name = "ctrl"
color = "Green"