# mode: conf-toml

data_timeout = 1
window_size = 10

[serial]
path = "/dev/tty.usbmodemBLIMP11"
# path = "/dev/ttys006"
baud = 9600

[[commands]]
name = "Surge 1"
command = "surge 1"
color = "Red"

[[commands]]
name = "Surge 0.1"
command = "surge .1"
color = "Yellow"

[[commands]]
name = "Roll +"
command = "roll+"
color = "Green"

[[commands]]
name = "Roll -"
command = "roll-"
color = "Green"

[[commands]]
name = "Pitch +"
command = "pitch+"
color = "Blue"

[[commands]]
name = "Pitch -"
command = "pitch-"
color = "Blue"

[[commands]]
name = "Yaw +"
command = "yaw+"
color = "Yellow"

[[commands]]
name = "Yaw -"
command = "yaw-"
color = "Yellow"

[[commands]]
name = "P Gain +"
command = "p+"
color = "Green"

[[commands]]
name = "P Gain -"
command = "p-"
color = "Green"

[[commands]]
name = "I Gain +"
command = "i+"
color = "Blue"

[[commands]]
name = "I Gain -"
command = "i-"
color = "Blue"

[[commands]]
name = "D Gain +"
command = "d+"
color = "Yellow"

[[commands]]
name = "D Gain -"
command = "d-"
color = "Yellow"

[[commands]]
name = "Test program"
command = "t"
color = "Orange"

[[commands]]
name = "Idle"
command = "idle"
color = "Red"

[[graphs]]
name = "VOT"
plots = [
    { name = "VOT", source_name = "vot", color = "Blue" },
]

[[graphs]]
name = "State"
plots = [
    { name = "State", source_name = "state", color = "Blue" },
]

[[graphs]]
name = "Rotation"
plots = [
    { name = "roll", source_name = "roll", color = "Red" },
    { name = "pitch", source_name = "pitch", color = "Blue" },
    { name = "yaw", source_name = "yaw", color = "Green" },
]

[[graphs]]
name = "Roll"
plots = [
    { name = "Setpoint", source_name = "set_roll", color = "Blue" },
    { name = "Roll", source_name = "roll", color = "Red" },
    { name = "SSE", source_name = "sse_roll", color = "Yellow" },
    { name = "Control", source_name = "ctrl_roll", color = "Green" },
]

[[graphs]]
name = "Pitch"
plots = [
    { name = "Setpoint", source_name = "set_pitch", color = "Blue" },
    { name = "Pitch", source_name = "pitch", color = "Red" },
    { name = "SSE", source_name = "sse_pitch", color = "Yellow" },
    { name = "Control", source_name = "ctrl_pitch", color = "Green" },
]

[[graphs]]
name = "Yaw"
plots = [
    { name = "Setpoint", source_name = "set_yaw", color = "Blue" },
    { name = "Yaw", source_name = "yaw", color = "Red" },
    { name = "SSE", source_name = "sse_yaw", color = "Yellow" },
    { name = "Control", source_name = "ctrl_yaw", color = "Green" },
]

[[graphs]]
name = "Surge"
plots = [
    { name = "Setpoint", source_name = "set_surge", color = "Blue" },
    { name = "Surge", source_name = "surge", color = "Red" },
    { name = "SSE", source_name = "sse_surge", color = "Yellow" },
    { name = "Control", source_name = "ctrl_surge", color = "Green" },
]

[[graphs]]
name = "Sway"
plots = [
    { name = "Setpoint", source_name = "set_sway", color = "Blue" },
    { name = "Sway", source_name = "sway", color = "Red" },
    { name = "SSE", source_name = "sse_sway", color = "Yellow" },
    { name = "Control", source_name = "ctrl_sway", color = "Green" },
]

[[graphs]]
name = "Heave"
plots = [
    { name = "Setpoint", source_name = "set_heave", color = "Blue" },
    { name = "Heave", source_name = "heave", color = "Red" },
    { name = "SSE", source_name = "sse_heave", color = "Yellow" },
    { name = "Control", source_name = "ctrl_heave", color = "Green" },
]

[[graphs]]
name = "PID gains"
plots = [
    { name = "P", source_name = "pgain", color = "Red" },
    { name = "I", source_name = "igain", color = "Blue" },
    { name = "D", source_name = "dgain", color = "Green" },
]

[[graphs]]
name = "Gyro"
plots = [
    { name = "gX", source_name = "gx", color = "Red" },
    { name = "gY", source_name = "gy", color = "Green" },
    { name = "gZ", source_name = "gz", color = "Yellow" },
]

[[graphs]]
name = "Accelerometer"
plots = [
    { name = "aX", source_name = "ax", color = "Red" },
    { name = "aY", source_name = "ay", color = "Green" },
    { name = "aZ", source_name = "az", color = "Yellow" },
]

[[graphs]]
name = "Rotation Quartenion"
plots = [
    { name = "i", source_name = "qi", color = "Red" },
    { name = "j", source_name = "qj", color = "Blue" },
    { name = "k", source_name = "qk", color = "Green" },
    { name = "w", source_name = "qw", color = "Yellow" },
]

[[graphs]]
name = "Kalman covariance"
plots = [
    { name = "11", source_name = "cov11", color = "Red" },
    { name = "22", source_name = "cov22", color = "Blue" },
    { name = "33", source_name = "cov33", color = "Green" },
    { name = "44", source_name = "cov44", color = "Yellow" },
    { name = "55", source_name = "cov55", color = "Red" },
    { name = "66", source_name = "cov66", color = "Blue" },
    { name = "77", source_name = "cov77", color = "Green" },
]
