# mode: conf-toml

data_timeout = 1
window_size = 10

[serial]
path = "/dev/ttys005"
baud = 9600

[[commands]]
name = "Setpoint +"
command = "s+"
color = "Blue"

[[commands]]
name = "Setpoint -"
command = "s-"
color = "Blue"

[[commands]]
name = "P Gain +"
command = "p+"
color = "Orange"

[[commands]]
name = "P Gain -"
command = "p-"
color = "Orange"

[[commands]]
name = "I Gain +"
command = "i+"
color = "Green"

[[commands]]
name = "I Gain -"
command = "i-"
color = "Green"

[[commands]]
name = "D Gain +"
command = "d+"
color = "Yellow"

[[commands]]
name = "D Gain -"
command = "d-"
color = "Yellow"

[[graphs]]
name = "VOT"
plots = [
    { name = "VOT", source_name = "vot", color = "Blue" },
]

[[graphs]]
name = "Kalman estimate"
plots = [
    { name = "Rot", source_name = "estrot", color = "Red" },
    { name = "Pos", source_name = "estpos", color = "Blue" },
]

[[graphs]]
name = "Kalman covariance"
plots = [
    { name = "11", source_name = "cov11", color = "Red" },
    { name = "12", source_name = "cov12", color = "Blue" },
    { name = "21", source_name = "cov21", color = "Green" },
    { name = "22", source_name = "cov22", color = "Yellow" },
]

[[graphs]]
name = "PID"
plots = [
    { name = "Setpoint", source_name = "set", color = "Blue" },
    { name = "Position", source_name = "estpos", color = "Red" },
    { name = "Steady state error", source_name = "sse", color = "Yellow" },
    { name = "Control", source_name = "ctrl", color = "Green" },
]

[[graphs]]
name = "PID gains"
plots = [
    { name = "P", source_name = "pgain", color = "Red" },
    { name = "I", source_name = "igain", color = "Blue" },
    { name = "D", source_name = "dgain", color = "Green" },
]

[[graphs]]
name = "Gyro"
plots = [
    { name = "gX", source_name = "gx", color = "Red" },
    { name = "gY", source_name = "gy", color = "Green" },
    { name = "gZ", source_name = "gz", color = "Yellow" },
]

[[graphs]]
name = "Accelerometer"
plots = [
    { name = "raw aX", source_name = "ax", color = "Red" },
    { name = "raw aY", source_name = "ay", color = "Green" },
    { name = "raw aZ", source_name = "az", color = "Yellow" },
]

[[graphs]]
name = "Accelerometer high-pass"
plots = [
    { name = "high aX", source_name = "hpax", color = "Red" },
    { name = "high aY", source_name = "hpay", color = "Green" },
    { name = "high aZ", source_name = "hpaz", color = "Yellow" },
]

[[graphs]]
name = "Accelerometer low-pass"
plots = [
    { name = "low aX", source_name = "lpax", color = "Red" },
    { name = "low aY", source_name = "lpay", color = "Green" },
    { name = "low aZ", source_name = "lpaz", color = "Yellow" },
]